import { getCurrentTheme, toggleTheme } from '@/redux/themeSlice'
import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import { Button } from 'antd'

export default function Home() {
  const theme = useSelector(getCurrentTheme)
  const dispatch = useDispatch()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main id={theme}>
        <div>{theme}</div>
        <Button onClick={() => dispatch(toggleTheme())}>Click</Button>
      </main>
    </>
  )
}
